[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_flags = -DPIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48_SECHEAP_SHARED
lib_deps = flova-platform/FlovaSDK@^0.2.0
extra_scripts = pre:$PROJECT_LIBDEPS_DIR/${PIOENV}/FlovaSDK/scripts/patch_esp8266_bearssl_nonblocking.py
