[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps = flova-platform/FlovaSDK@^0.3.6
build_flags =
  -DPIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48_SECHEAP_SHARED
