[env:esp8266-touch-led]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps = knolleary/PubSubClient@^2.8
lib_extra_dirs = ../../packages
build_flags =
  -I../../packages/flova-device-sdk/include
  -I../../packages/flova-arduino/include
  -I../../packages/flova-esp8266/include
