#!/usr/bin/env python3
"""Generate deterministic Flova Link v1 CBOR/frame conformance vectors.

This intentionally tiny encoder is test tooling, not a protocol runtime. The
checked-in vectors are validated by the generated zcbor decoder and the Engine
codec tests.
"""

import json
import struct
from pathlib import Path


class F32(float):
    pass


class F64(float):
    pass


def head(major, value):
    if value < 24:
        return bytes([(major << 5) | value])
    if value <= 0xFF:
        return bytes([(major << 5) | 24, value])
    if value <= 0xFFFF:
        return bytes([(major << 5) | 25]) + struct.pack(">H", value)
    if value <= 0xFFFFFFFF:
        return bytes([(major << 5) | 26]) + struct.pack(">I", value)
    return bytes([(major << 5) | 27]) + struct.pack(">Q", value)


def encode(value):
    if value is False:
        return b"\xf4"
    if value is True:
        return b"\xf5"
    if isinstance(value, F32):
        return b"\xfa" + struct.pack(">f", value)
    if isinstance(value, F64):
        return b"\xfb" + struct.pack(">d", value)
    if isinstance(value, int):
        return head(0, value) if value >= 0 else head(1, -1 - value)
    if isinstance(value, bytes):
        return head(2, len(value)) + value
    if isinstance(value, str):
        raw = value.encode("utf-8")
        return head(3, len(raw)) + raw
    if isinstance(value, list):
        return head(4, len(value)) + b"".join(encode(item) for item in value)
    if isinstance(value, dict):
        items = sorted(((encode(key), encode(item)) for key, item in value.items()),
                       key=lambda pair: (len(pair[0]), pair[0]))
        return head(5, len(items)) + b"".join(key + item for key, item in items)
    raise TypeError(type(value).__name__)


UUID1 = bytes.fromhex("00112233445566778899aabbccddeeff")
UUID2 = bytes.fromhex("ffeeddccbbaa99887766554433221100")
SECRET = bytes(range(32))
SHA = bytes.fromhex("a5" * 32)
CAPS = {0: 100, 1: 16, 2: 16, 3: 8, 4: 32, 5: 2048, 6: 1024, 7: 512}

VECTORS = [
    (0x01, "auth", [UUID1, SECRET]),
    (0x02, "auth_ok", [1_800_000_000_000, 30_000, 512, 7]),
    (0x03, "auth_error", ["invalid_credentials"]),
    (0x04, "ping", []),
    (0x05, "pong", []),
    (0x06, "bootstrap_auth", {0: b"t" * 32, 1: SECRET, 2: "esp-aabbcc", 3: "universal-esp8266", 4: CAPS}),
    (0x07, "bootstrap_committed", [UUID1, 7, 1_800_000_000_000]),
    (0x08, "bootstrap_error", ["invalid_provision_token"]),
    (0x09, "datastream_bind", [7, ["temperature", "humidity", "relay"]]),
    (0x0A, "datastream_bound", [7, [17, 18, 19]]),
    (0x10, "heartbeat", [7, 123_456, 1, "1.0.0"]),
    (0x11, "state", [7, [[1, 0, True, 9], [2, 2, F32(21.5), 10]]]),
    (0x12, "command_result", [7, UUID1, 1, 0, 0, True, 9, b""]),
    (0x13, "config_reported", [7, 0, SHA]),
    (0x14, "ota_reported", [UUID1, 2, "ok", 100]),
    (0x15, "schedule_reported", [7, 12, 0, SHA]),
    (0x16, "schedule_renew", [7, 12]),
    (0x17, "time_request", [42, 123_456]),
    (0x18, "config_ack", [7, 3, 0, "ok"]),
    (0x20, "command", [7, UUID1, 1, 3, F64(42.25), 9, 1_800_000_030_000, UUID2]),
    (0x21, "ingestion_ack", []),
    (0x22, "config_desired", [8, SHA, 3]),
    (0x23, "ota_desired", {0: UUID1, 1: "1.1.0", 2: "https://fw.flova.dev/a.bin", 3: SHA, 4: 262144, 5: "universal-esp8266"}),
    (0x24, "schedule_desired", [7, 13, 1, SHA]),
    (0x25, "time_response", [42, 1_800_000_000_000]),
    (0x26, "flow_control", [5_000, "overloaded", 8]),
    (0x27, "message_rejected", ["invalid_state"]),
    (0x28, "config_begin", {0: 8, 1: 1, 2: SHA, 3: 2, 4: CAPS, 5: UUID1, 6: UUID2, 7: "wss://link.flova.dev/device", 8: UUID1}),
    (0x29, "config_record", {0: 8, 1: 0, 2: {0: 0, 1: 1, 2: UUID1, 3: "relay", 4: 0, 7: [0, False], 8: {0: 1, 1: 5, 2: True, 6: 300}}}),
    (0x2A, "config_end", [8, 2, SHA]),
    (0x2B, "schedule_record", [8, 0, {0: 2, 1: 12, 2: True, 3: 1_800_000_000_000, 4: 1_800_086_400_000, 5: [[0, 1, 0, True]]}]),
    (0x2C, "schedule_end", [8, 1, SHA]),
    (0x7F, "error", ["malformed_payload"]),
]


def main():
    rows = []
    headers = [
        "/* Generated by scripts/generate_flova_link_vectors.py. */",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "struct FlovaLinkVector {",
        "  const char* name;",
        "  uint8_t message_type;",
        "  uint64_t message_id;",
        "  const uint8_t* frame;",
        "  size_t frame_size;",
        "};",
        "",
    ]
    entries = []
    for index, (message_type, name, semantic) in enumerate(VECTORS, 1):
        payload = encode(semantic)
        frame = bytes([message_type, 0]) + struct.pack(">H", len(payload)) + struct.pack(">Q", index) + payload
        if len(frame) > 512:
            raise ValueError(f"{name} vector exceeds frame limit")
        rows.append({
            "name": name,
            "message_type": message_type,
            "message_id": index,
            "payload_hex": payload.hex(),
            "frame_hex": frame.hex(),
        })
        symbol = f"flova_link_vector_{name}"
        encoded = ", ".join(f"0x{byte:02x}" for byte in frame)
        headers.append(f"static const uint8_t {symbol}[] = {{{encoded}}};")
        entries.append(
            f'  {{"{name}", 0x{message_type:02x}, {index}ULL, {symbol}, sizeof({symbol})}}'
        )
    output = Path(__file__).resolve().parents[1] / "protocol" / "conformance-vectors.json"
    output.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")
    headers.extend([
        "",
        "static const FlovaLinkVector flova_link_vectors[] = {",
        ",\n".join(entries),
        "};",
        "static const size_t flova_link_vector_count =",
        "    sizeof(flova_link_vectors) / sizeof(flova_link_vectors[0]);",
        "",
    ])
    header = output.parent / "generated" / "firmware" / "include" / "flova_link_vectors.h"
    header.write_text("\n".join(headers), encoding="utf-8")


if __name__ == "__main__":
    main()
