[env:universal-esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = knolleary/PubSubClient@^2.8
lib_extra_dirs = ../../packages
build_flags =
  -I../../packages/flova-device-sdk/include
  -I../../packages/flova-arduino/include
  -I../../packages/flova-esp32/include
